name: loop_splat
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - cuda-toolkit=12.8.0
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch
    - torchvision
    - faiss-gpu-cu12
    - setuptools==69.5.1
    - open3d==0.19.0
    - wandb
    - trimesh==4.0.10
    - pytorch_msssim
    - torchmetrics
    - tqdm
    - imageio
    - opencv-python
    - plyfile
    - roma
    - einops==0.8.0
    - numpy==1.26.4
    - PyQt5==5.15.11
    - matplotlib==3.10.8
    - evo==1.11.0
    - python-pycg